version: '3.8'

services:
  db:
    container_name: bookmarks-db
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ySB9nz6bdx9hNj
      POSTGRES_DB: postgres
    volumes:
      # - ./volumes/db/data:/var/lib/postgresql/data
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
